name: Run Test Docker Container and Save Logs

on:
  push:
    branches:
      - main

jobs:
  run-docker-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build the Docker container
      - name: Build Docker Image
        run: |
          docker build -t test-docker-image .

      # Run the Docker container and capture logs
      - name: Run Docker Container
        run: |
          docker run --rm test-docker-image > stdout.log 2> stderr.log || true

      # Upload logs as artifacts
      - name: Upload Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            stdout.log
            stderr.log
